# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r
r: release
cache: packages

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

env:
   global:
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
     
warnings_are_errors: true
r_check_args: --as-cran 

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'lintr::lint_package()'
  
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  
notifications:
  email:
    on_success: change
    on_failure: change

